/**
 * Server functions for AI-visibility analysis: Share of Voice. Read-only —
 * derived entirely from existing prompt_runs data via the postgres read layer
 * plus the pure stats in `@/lib/visibility-stats`. No schema changes.
 *
 * Filters are resolved server-side (tags/search -> prompt IDs) via
 * `resolveFilteredPrompts`, and the lookback window is computed in the user's
 * timezone — the same handling as the visibility page (see issue #68), so we
 * never serialize a brand's full prompt-id list into the request URL.
 *
 * The Opportunities page is generated by an LLM and lives in `server/opportunities.ts`.
 */
import { createServerFn } from "@tanstack/react-start";
import { db } from "@workspace/lib/db/db";
import { brands } from "@workspace/lib/db/schema";
import { eq } from "drizzle-orm";
import { z } from "zod";
import { requireAuthSession, requireOrgAccess } from "@/lib/auth/helpers";
import { coerceLookbackPeriod, generateDateRange, type LookbackPeriod } from "@/lib/chart-utils";
import {
	getBrandMentionTotals,
	getPerPromptDailyCompetitorMentions,
	getPerPromptDailyMentions,
} from "@/lib/postgres-read";
import { APP_TIMEZONE } from "@/lib/app-locale";
import { getTimezoneLookbackRange, resolveTimezone } from "@/lib/timezone-utils";
import { computeShareOfVoice, shareOfVoiceLeaderboardLVCF, shareOfVoiceTimeSeriesLVCF } from "@/lib/visibility-stats";
import { resolveFilteredPrompts } from "@/server/prompt-resolution";

/** Accepts the presets plus `custom:YYYY-MM-DD:YYYY-MM-DD`; anything unrecognised
 *  degrades to the default one-month window rather than failing the request. */
export const LOOKBACK = z.string().transform((value) => coerceLookbackPeriod(value));

/** Resolve a lookback + timezone into concrete from/to date strings (mirrors server/visibility.ts). */
export function resolveRange(lookback: LookbackPeriod, timezoneParam: string) {
	const timezone = resolveTimezone(timezoneParam);
	const { fromDateStr, toDateStr } = getTimezoneLookbackRange(lookback, timezone, { allStrategy: "1y" }) as {
		fromDateStr: string;
		toDateStr: string;
	};
	return { timezone, fromDateStr, toDateStr };
}

// ============================================================================
// Share of Voice
// ============================================================================

export interface ShareOfVoiceEntry {
	name: string;
	mentions: number;
	share: number;
	isBrand: boolean;
	/** Distinct prompts the entity appeared in. */
	prompts: number;
}

export interface ShareOfVoiceResponse {
	brandName: string;
	entries: ShareOfVoiceEntry[];
	brandShare: number | null;
	totalRuns: number;
	model: string | null;
	/** Brand share of voice over time (percentage 0..100, null on days with no runs). */
	shareTimeSeries: Array<{ date: string; share: number | null }>;
}

export const getShareOfVoiceFn = createServerFn({ method: "GET" })
	.validator(
		z.object({
			brandId: z.string(),
			lookback: LOOKBACK.default("1m"),
			model: z.string().optional(),
			tags: z.string().optional(),
			search: z.string().optional(),
			timezone: z.string().default(APP_TIMEZONE),
		}),
	)
	.handler(async ({ data }): Promise<ShareOfVoiceResponse> => {
		const session = await requireAuthSession();
		await requireOrgAccess(session.user.id, data.brandId);

		const { timezone, fromDateStr, toDateStr } = resolveRange(data.lookback as LookbackPeriod, data.timezone);

		const [brandRow, resolved] = await Promise.all([
			db.select({ name: brands.name }).from(brands).where(eq(brands.id, data.brandId)).limit(1),
			resolveFilteredPrompts(data.brandId, { tags: data.tags, search: data.search }),
		]);
		const brandName = brandRow[0]?.name ?? "Your brand";
		const promptIds = resolved.map((p) => p.id);

		if (promptIds.length === 0) {
			return { brandName, entries: [], brandShare: null, totalRuns: 0, model: data.model ?? null, shareTimeSeries: [] };
		}

		const dateRange = generateDateRange(new Date(fromDateStr), new Date(toDateStr));
		const [totals, perPromptDaily, perPromptCompetitorDaily] = await Promise.all([
			getBrandMentionTotals(data.brandId, fromDateStr, toDateStr, timezone, promptIds, data.model),
			getPerPromptDailyMentions(data.brandId, fromDateStr, toDateStr, timezone, promptIds, data.model),
			getPerPromptDailyCompetitorMentions(data.brandId, fromDateStr, toDateStr, timezone, promptIds, data.model),
		]);

		// "Current standings": carry each prompt's latest brand + per-competitor counts
		// forward to the last day, so the headline, donut, and leaderboard reflect the
		// same state as the trend's final point rather than a whole-window aggregate.
		const standings = shareOfVoiceLeaderboardLVCF(
			perPromptDaily.map((r) => ({ promptId: r.prompt_id, date: String(r.date), brand: r.brand_mentions })),
			perPromptCompetitorDaily.map((r) => ({
				promptId: r.prompt_id,
				date: String(r.date),
				competitor: r.competitor,
				mentions: r.mentions,
			})),
			dateRange,
		);

		const promptsByName = new Map(standings.competitors.map((c) => [c.name, c.prompts]));
		const { entries, brandShare } = computeShareOfVoice(
			{ name: brandName, mentions: standings.brandMentions },
			standings.competitors.map((c) => ({ name: c.name, mentions: c.mentions })),
		);

		// Same per-prompt LVCF as the standings above, per day — so the line's final
		// point equals the headline brandShare.
		const shareTimeSeries = shareOfVoiceTimeSeriesLVCF(
			perPromptDaily.map((r) => ({
				promptId: r.prompt_id,
				date: String(r.date),
				brandMentions: r.brand_mentions,
				competitorMentions: r.competitor_mentions,
			})),
			dateRange,
		);

		return {
			brandName,
			brandShare,
			totalRuns: totals.total_runs,
			model: data.model ?? null,
			shareTimeSeries,
			entries: entries.map((e) => ({
				...e,
				prompts: e.isBrand ? standings.brandPrompts : (promptsByName.get(e.name) ?? 0),
			})),
		};
	});
